# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/audiophil.ui'
#
# Created: Sat Jan 24 10:10:59 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AudioPhil(object):
    def setupUi(self, AudioPhil):
        AudioPhil.setObjectName(_fromUtf8("AudioPhil"))
        AudioPhil.resize(800, 566)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/audiophil.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AudioPhil.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(AudioPhil)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.playlists = Playlists(self.centralwidget)
        self.playlists.setObjectName(_fromUtf8("playlists"))
        self.verticalLayout_2.addWidget(self.playlists)
        AudioPhil.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AudioPhil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAudioPhil = QtGui.QMenu(self.menubar)
        self.menuAudioPhil.setObjectName(_fromUtf8("menuAudioPhil"))
        self.menuPlayer = QtGui.QMenu(self.menubar)
        self.menuPlayer.setObjectName(_fromUtf8("menuPlayer"))
        self.menuPlay_Order = QtGui.QMenu(self.menuPlayer)
        self.menuPlay_Order.setObjectName(_fromUtf8("menuPlay_Order"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuPlaylist = QtGui.QMenu(self.menubar)
        self.menuPlaylist.setObjectName(_fromUtf8("menuPlaylist"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        AudioPhil.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(AudioPhil)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        AudioPhil.setStatusBar(self.statusbar)
        self.controlsToolBar = QtGui.QToolBar(AudioPhil)
        self.controlsToolBar.setFloatable(False)
        self.controlsToolBar.setObjectName(_fromUtf8("controlsToolBar"))
        AudioPhil.addToolBar(QtCore.Qt.TopToolBarArea, self.controlsToolBar)
        self.volumeToolBar = QtGui.QToolBar(AudioPhil)
        self.volumeToolBar.setFloatable(False)
        self.volumeToolBar.setObjectName(_fromUtf8("volumeToolBar"))
        AudioPhil.addToolBar(QtCore.Qt.TopToolBarArea, self.volumeToolBar)
        self.seekToolBar = QtGui.QToolBar(AudioPhil)
        self.seekToolBar.setFloatable(False)
        self.seekToolBar.setObjectName(_fromUtf8("seekToolBar"))
        AudioPhil.addToolBar(QtCore.Qt.TopToolBarArea, self.seekToolBar)
        self.mediaLibrary = MediaLibrary(AudioPhil)
        self.mediaLibrary.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.mediaLibrary.setObjectName(_fromUtf8("mediaLibrary"))
        self.mediaLibraryLayout = QtGui.QWidget()
        self.mediaLibraryLayout.setObjectName(_fromUtf8("mediaLibraryLayout"))
        self.mediaLibrary.setWidget(self.mediaLibraryLayout)
        AudioPhil.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.mediaLibrary)
        self.sidebar = QtGui.QDockWidget(AudioPhil)
        self.sidebar.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.sidebar.setObjectName(_fromUtf8("sidebar"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea_2 = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 171, 425))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.fileInfo = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.fileInfo.setStyleSheet(_fromUtf8("/*\n"
"QGroupBox::indicator:unchecked { \n"
"    image: url(:/icons/player_stop.svg); \n"
"}\n"
"QGroupBox::indicator:unchecked:hover {\n"
"    image: url(:/icons/player_stop.svg); \n"
"}    \n"
"QGroupBox::indicator:unchecked:pressed {\n"
"    image: url(:/icons/player_stop.svg); \n"
"}\n"
"\n"
"QGroupBox::indicator:checked {\n"
"    image: url(:/icons/player_play.svg); \n"
"}\n"
"QGroupBox::indicator:checked:hover {\n"
"    image: url(:/icons/player_play.svg); \n"
"}\n"
"QGroupBox::indicator:checked:pressed {\n"
"    image: url(:/icons/player_play.svg); \n"
"}\n"
"*/"))
        self.fileInfo.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.fileInfo.setCheckable(True)
        self.fileInfo.setObjectName(_fromUtf8("fileInfo"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.fileInfo)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.fileInfoChildren = QtGui.QWidget(self.fileInfo)
        self.fileInfoChildren.setObjectName(_fromUtf8("fileInfoChildren"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.fileInfoChildren)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_22 = QtGui.QLabel(self.fileInfoChildren)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_13.addWidget(self.label_22)
        self.fileNameLineEdit = QtGui.QLineEdit(self.fileInfoChildren)
        self.fileNameLineEdit.setFrame(False)
        self.fileNameLineEdit.setReadOnly(True)
        self.fileNameLineEdit.setObjectName(_fromUtf8("fileNameLineEdit"))
        self.verticalLayout_13.addWidget(self.fileNameLineEdit)
        self.label_23 = QtGui.QLabel(self.fileInfoChildren)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_13.addWidget(self.label_23)
        self.filePathLineEdit = QtGui.QLineEdit(self.fileInfoChildren)
        self.filePathLineEdit.setText(_fromUtf8(""))
        self.filePathLineEdit.setFrame(False)
        self.filePathLineEdit.setReadOnly(True)
        self.filePathLineEdit.setObjectName(_fromUtf8("filePathLineEdit"))
        self.verticalLayout_13.addWidget(self.filePathLineEdit)
        self.label_24 = QtGui.QLabel(self.fileInfoChildren)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_13.addWidget(self.label_24)
        self.fileSizeLineEdit = QtGui.QLineEdit(self.fileInfoChildren)
        self.fileSizeLineEdit.setFrame(False)
        self.fileSizeLineEdit.setReadOnly(True)
        self.fileSizeLineEdit.setObjectName(_fromUtf8("fileSizeLineEdit"))
        self.verticalLayout_13.addWidget(self.fileSizeLineEdit)
        self.verticalLayout_12.addWidget(self.fileInfoChildren)
        self.verticalLayout_11.addWidget(self.fileInfo)
        self.metadata = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.metadata.setCheckable(True)
        self.metadata.setObjectName(_fromUtf8("metadata"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.metadata)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.metadataChildren = QtGui.QWidget(self.metadata)
        self.metadataChildren.setObjectName(_fromUtf8("metadataChildren"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.metadataChildren)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_7 = QtGui.QPushButton(self.metadataChildren)
        self.pushButton_7.setEnabled(False)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_5.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.metadataChildren)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_5.addWidget(self.pushButton_8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.label_25 = QtGui.QLabel(self.metadataChildren)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_15.addWidget(self.label_25)
        self.artistLineEdit = QtGui.QLineEdit(self.metadataChildren)
        self.artistLineEdit.setObjectName(_fromUtf8("artistLineEdit"))
        self.verticalLayout_15.addWidget(self.artistLineEdit)
        self.label_26 = QtGui.QLabel(self.metadataChildren)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_15.addWidget(self.label_26)
        self.albumLineEdit = QtGui.QLineEdit(self.metadataChildren)
        self.albumLineEdit.setObjectName(_fromUtf8("albumLineEdit"))
        self.verticalLayout_15.addWidget(self.albumLineEdit)
        self.label_27 = QtGui.QLabel(self.metadataChildren)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_15.addWidget(self.label_27)
        self.trackLineEdit = QtGui.QLineEdit(self.metadataChildren)
        self.trackLineEdit.setObjectName(_fromUtf8("trackLineEdit"))
        self.verticalLayout_15.addWidget(self.trackLineEdit)
        self.label_28 = QtGui.QLabel(self.metadataChildren)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_15.addWidget(self.label_28)
        self.tracknumberSpinBox = QtGui.QSpinBox(self.metadataChildren)
        self.tracknumberSpinBox.setObjectName(_fromUtf8("tracknumberSpinBox"))
        self.verticalLayout_15.addWidget(self.tracknumberSpinBox)
        self.verticalLayout_14.addWidget(self.metadataChildren)
        self.verticalLayout_11.addWidget(self.metadata)
        spacerItem = QtGui.QSpacerItem(20, 7, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea_2)
        self.sidebar.setWidget(self.dockWidgetContents)
        AudioPhil.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.sidebar)
        self.currentlyPlaying = QtGui.QDockWidget(AudioPhil)
        self.currentlyPlaying.setObjectName(_fromUtf8("currentlyPlaying"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.activeSongInfoLabel = QtGui.QLabel(self.dockWidgetContents_2)
        self.activeSongInfoLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.activeSongInfoLabel.setObjectName(_fromUtf8("activeSongInfoLabel"))
        self.horizontalLayout.addWidget(self.activeSongInfoLabel)
        self.activeSongPixmapLabel = QtGui.QLabel(self.dockWidgetContents_2)
        self.activeSongPixmapLabel.setText(_fromUtf8(""))
        self.activeSongPixmapLabel.setObjectName(_fromUtf8("activeSongPixmapLabel"))
        self.horizontalLayout.addWidget(self.activeSongPixmapLabel)
        self.currentlyPlaying.setWidget(self.dockWidgetContents_2)
        AudioPhil.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.currentlyPlaying)
        self.configureAction = QtGui.QAction(AudioPhil)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/config.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configureAction.setIcon(icon1)
        self.configureAction.setObjectName(_fromUtf8("configureAction"))
        self.quitAction = QtGui.QAction(AudioPhil)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fileclose.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon2)
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.playerPreviousAction = QtGui.QAction(AudioPhil)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/player_start.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playerPreviousAction.setIcon(icon3)
        self.playerPreviousAction.setObjectName(_fromUtf8("playerPreviousAction"))
        self.playerPlayAction = QtGui.QAction(AudioPhil)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/player_play.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playerPlayAction.setIcon(icon4)
        self.playerPlayAction.setObjectName(_fromUtf8("playerPlayAction"))
        self.playerPauseAction = QtGui.QAction(AudioPhil)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/player_pause.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playerPauseAction.setIcon(icon5)
        self.playerPauseAction.setObjectName(_fromUtf8("playerPauseAction"))
        self.playerStopAction = QtGui.QAction(AudioPhil)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/player_stop.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playerStopAction.setIcon(icon6)
        self.playerStopAction.setObjectName(_fromUtf8("playerStopAction"))
        self.playerNextAction = QtGui.QAction(AudioPhil)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/player_end.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playerNextAction.setIcon(icon7)
        self.playerNextAction.setObjectName(_fromUtf8("playerNextAction"))
        self.playbackFollowCursorAction = QtGui.QAction(AudioPhil)
        self.playbackFollowCursorAction.setCheckable(True)
        self.playbackFollowCursorAction.setChecked(True)
        self.playbackFollowCursorAction.setObjectName(_fromUtf8("playbackFollowCursorAction"))
        self.cursorFollowPlaybackAction = QtGui.QAction(AudioPhil)
        self.cursorFollowPlaybackAction.setCheckable(True)
        self.cursorFollowPlaybackAction.setChecked(True)
        self.cursorFollowPlaybackAction.setObjectName(_fromUtf8("cursorFollowPlaybackAction"))
        self.newPlaylistAction = QtGui.QAction(AudioPhil)
        self.newPlaylistAction.setObjectName(_fromUtf8("newPlaylistAction"))
        self.removePlaylistAction = QtGui.QAction(AudioPhil)
        self.removePlaylistAction.setObjectName(_fromUtf8("removePlaylistAction"))
        self.playlistAddAction = QtGui.QAction(AudioPhil)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/playlist_add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playlistAddAction.setIcon(icon8)
        self.playlistAddAction.setObjectName(_fromUtf8("playlistAddAction"))
        self.playlistRemoveAction = QtGui.QAction(AudioPhil)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/playlist_remove.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playlistRemoveAction.setIcon(icon9)
        self.playlistRemoveAction.setObjectName(_fromUtf8("playlistRemoveAction"))
        self.muteAction = QtGui.QAction(AudioPhil)
        self.muteAction.setCheckable(True)
        self.muteAction.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/volume-med.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.muteAction.setIcon(icon10)
        self.muteAction.setObjectName(_fromUtf8("muteAction"))
        self.renamePlaylistAction = QtGui.QAction(AudioPhil)
        self.renamePlaylistAction.setObjectName(_fromUtf8("renamePlaylistAction"))
        self.playbackModeRepeatTrackAction = QtGui.QAction(AudioPhil)
        self.playbackModeRepeatTrackAction.setCheckable(True)
        self.playbackModeRepeatTrackAction.setObjectName(_fromUtf8("playbackModeRepeatTrackAction"))
        self.playbackModeRepeatPlaylistAction = QtGui.QAction(AudioPhil)
        self.playbackModeRepeatPlaylistAction.setCheckable(True)
        self.playbackModeRepeatPlaylistAction.setObjectName(_fromUtf8("playbackModeRepeatPlaylistAction"))
        self.playbackModeRandomAction = QtGui.QAction(AudioPhil)
        self.playbackModeRandomAction.setCheckable(True)
        self.playbackModeRandomAction.setObjectName(_fromUtf8("playbackModeRandomAction"))
        self.playbackModeRandomPlaylistAction = QtGui.QAction(AudioPhil)
        self.playbackModeRandomPlaylistAction.setCheckable(True)
        self.playbackModeRandomPlaylistAction.setEnabled(False)
        self.playbackModeRandomPlaylistAction.setObjectName(_fromUtf8("playbackModeRandomPlaylistAction"))
        self.stopAfterCurrentAction = QtGui.QAction(AudioPhil)
        self.stopAfterCurrentAction.setCheckable(True)
        self.stopAfterCurrentAction.setObjectName(_fromUtf8("stopAfterCurrentAction"))
        self.playlistSearchAction = QtGui.QAction(AudioPhil)
        self.playlistSearchAction.setObjectName(_fromUtf8("playlistSearchAction"))
        self.actionAbout = QtGui.QAction(AudioPhil)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.savePlaylistAction = QtGui.QAction(AudioPhil)
        self.savePlaylistAction.setObjectName(_fromUtf8("savePlaylistAction"))
        self.showSidebarAction = QtGui.QAction(AudioPhil)
        self.showSidebarAction.setCheckable(True)
        self.showSidebarAction.setObjectName(_fromUtf8("showSidebarAction"))
        self.showMediaLibraryAction = QtGui.QAction(AudioPhil)
        self.showMediaLibraryAction.setCheckable(True)
        self.showMediaLibraryAction.setObjectName(_fromUtf8("showMediaLibraryAction"))
        self.openPlaylistsAction = QtGui.QAction(AudioPhil)
        self.openPlaylistsAction.setObjectName(_fromUtf8("openPlaylistsAction"))
        self.menuAudioPhil.addAction(self.configureAction)
        self.menuAudioPhil.addSeparator()
        self.menuAudioPhil.addAction(self.quitAction)
        self.menuPlay_Order.addAction(self.playbackModeRepeatTrackAction)
        self.menuPlay_Order.addAction(self.playbackModeRepeatPlaylistAction)
        self.menuPlay_Order.addAction(self.playbackModeRandomAction)
        self.menuPlay_Order.addAction(self.playbackModeRandomPlaylistAction)
        self.menuPlayer.addAction(self.playerPreviousAction)
        self.menuPlayer.addAction(self.playerPlayAction)
        self.menuPlayer.addAction(self.playerPauseAction)
        self.menuPlayer.addAction(self.playerStopAction)
        self.menuPlayer.addAction(self.playerNextAction)
        self.menuPlayer.addSeparator()
        self.menuPlayer.addAction(self.muteAction)
        self.menuPlayer.addSeparator()
        self.menuPlayer.addAction(self.menuPlay_Order.menuAction())
        self.menuPlayer.addAction(self.playbackFollowCursorAction)
        self.menuPlayer.addAction(self.cursorFollowPlaybackAction)
        self.menuPlayer.addAction(self.stopAfterCurrentAction)
        self.menuHelp.addAction(self.actionAbout)
        self.menuPlaylist.addAction(self.newPlaylistAction)
        self.menuPlaylist.addAction(self.openPlaylistsAction)
        self.menuPlaylist.addAction(self.savePlaylistAction)
        self.menuPlaylist.addAction(self.renamePlaylistAction)
        self.menuPlaylist.addAction(self.removePlaylistAction)
        self.menuPlaylist.addSeparator()
        self.menuPlaylist.addAction(self.playlistAddAction)
        self.menuPlaylist.addAction(self.playlistRemoveAction)
        self.menubar.addAction(self.menuAudioPhil.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuPlayer.menuAction())
        self.menubar.addAction(self.menuPlaylist.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.controlsToolBar.addAction(self.playerPreviousAction)
        self.controlsToolBar.addAction(self.playerPlayAction)
        self.controlsToolBar.addAction(self.playerPauseAction)
        self.controlsToolBar.addAction(self.playerStopAction)
        self.controlsToolBar.addAction(self.playerNextAction)

        self.retranslateUi(AudioPhil)
        QtCore.QObject.connect(self.quitAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.close)
        QtCore.QObject.connect(self.configureAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.config)
        QtCore.QObject.connect(self.playerNextAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.playNext)
        QtCore.QObject.connect(self.playerPlayAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.play)
        QtCore.QObject.connect(self.playerPauseAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.pause)
        QtCore.QObject.connect(self.playerStopAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.stop)
        QtCore.QObject.connect(self.playerPreviousAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.previous)
        QtCore.QObject.connect(self.playlistAddAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.addPlaylistItems)
        QtCore.QObject.connect(self.playlistRemoveAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.removePlaylistItems)
        QtCore.QObject.connect(self.muteAction, QtCore.SIGNAL(_fromUtf8("triggered(bool)")), AudioPhil.setMute)
        QtCore.QObject.connect(self.playbackModeRandomAction, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.playbackModeRandomPlaylistAction.setEnabled)
        QtCore.QObject.connect(self.playlistSearchAction, QtCore.SIGNAL(_fromUtf8("triggered()")), self.playlists.onSearchPlaylist)
        QtCore.QObject.connect(self.renamePlaylistAction, QtCore.SIGNAL(_fromUtf8("triggered()")), self.playlists.onRenamePlaylist)
        QtCore.QObject.connect(self.removePlaylistAction, QtCore.SIGNAL(_fromUtf8("triggered()")), self.playlists.onRemovePlaylist)
        QtCore.QObject.connect(self.newPlaylistAction, QtCore.SIGNAL(_fromUtf8("triggered()")), self.playlists.addEmptyPlaylist)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.helpAbout)
        QtCore.QObject.connect(self.savePlaylistAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.onSavePlaylist)
        QtCore.QObject.connect(self.metadata, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.metadataChildren.setVisible)
        QtCore.QObject.connect(self.fileInfo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.fileInfoChildren.setVisible)
        QtCore.QObject.connect(self.openPlaylistsAction, QtCore.SIGNAL(_fromUtf8("triggered()")), AudioPhil.onOpenPlaylists)
        QtCore.QMetaObject.connectSlotsByName(AudioPhil)

    def retranslateUi(self, AudioPhil):
        AudioPhil.setWindowTitle(_translate("AudioPhil", "AudioPhil", None))
        self.menuAudioPhil.setTitle(_translate("AudioPhil", "&AudioPhil", None))
        self.menuPlayer.setTitle(_translate("AudioPhil", "&Player", None))
        self.menuPlay_Order.setTitle(_translate("AudioPhil", "Play Order", None))
        self.menuHelp.setTitle(_translate("AudioPhil", "Help", None))
        self.menuPlaylist.setTitle(_translate("AudioPhil", "Play&list", None))
        self.menuView.setTitle(_translate("AudioPhil", "&View", None))
        self.controlsToolBar.setWindowTitle(_translate("AudioPhil", "Controls Toolbar", None))
        self.volumeToolBar.setWindowTitle(_translate("AudioPhil", "Volume Toolbar", None))
        self.seekToolBar.setWindowTitle(_translate("AudioPhil", "Seek Toolbar", None))
        self.mediaLibrary.setWindowTitle(_translate("AudioPhil", "Media Library", None))
        self.sidebar.setWindowTitle(_translate("AudioPhil", "Sidebar", None))
        self.fileInfo.setTitle(_translate("AudioPhil", "File Info", None))
        self.label_22.setText(_translate("AudioPhil", "File Name", None))
        self.label_23.setText(_translate("AudioPhil", "File Path", None))
        self.label_24.setText(_translate("AudioPhil", "File Size", None))
        self.metadata.setTitle(_translate("AudioPhil", "Metadata", None))
        self.pushButton_7.setText(_translate("AudioPhil", "Revert", None))
        self.pushButton_8.setText(_translate("AudioPhil", "Apply", None))
        self.label_25.setText(_translate("AudioPhil", "Artist", None))
        self.label_26.setText(_translate("AudioPhil", "Album", None))
        self.label_27.setText(_translate("AudioPhil", "Trackname", None))
        self.label_28.setText(_translate("AudioPhil", "Tracknumber", None))
        self.currentlyPlaying.setWindowTitle(_translate("AudioPhil", "currently Playing", None))
        self.activeSongInfoLabel.setText(_translate("AudioPhil", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Not playing</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">by (No Artist)</span></p></body></html>", None))
        self.configureAction.setText(_translate("AudioPhil", "Configure AudioPhil...", None))
        self.quitAction.setText(_translate("AudioPhil", "Quit", None))
        self.quitAction.setShortcut(_translate("AudioPhil", "Ctrl+Q", None))
        self.playerPreviousAction.setText(_translate("AudioPhil", "Previous", None))
        self.playerPreviousAction.setShortcut(_translate("AudioPhil", "Y", None))
        self.playerPlayAction.setText(_translate("AudioPhil", "Play", None))
        self.playerPlayAction.setShortcut(_translate("AudioPhil", "X", None))
        self.playerPauseAction.setText(_translate("AudioPhil", "Pause", None))
        self.playerPauseAction.setShortcut(_translate("AudioPhil", "C", None))
        self.playerStopAction.setText(_translate("AudioPhil", "Stop", None))
        self.playerStopAction.setShortcut(_translate("AudioPhil", "V", None))
        self.playerNextAction.setText(_translate("AudioPhil", "Next", None))
        self.playerNextAction.setShortcut(_translate("AudioPhil", "B", None))
        self.playbackFollowCursorAction.setText(_translate("AudioPhil", "Playback follows Cursor", None))
        self.cursorFollowPlaybackAction.setText(_translate("AudioPhil", "Cursor follows Playback", None))
        self.newPlaylistAction.setText(_translate("AudioPhil", "New Playlist", None))
        self.newPlaylistAction.setShortcut(_translate("AudioPhil", "Ctrl+N", None))
        self.removePlaylistAction.setText(_translate("AudioPhil", "Remove current Playlist", None))
        self.removePlaylistAction.setShortcut(_translate("AudioPhil", "Ctrl+W", None))
        self.playlistAddAction.setText(_translate("AudioPhil", "Add to playlist", None))
        self.playlistAddAction.setToolTip(_translate("AudioPhil", "Add media to the current playlist", None))
        self.playlistRemoveAction.setText(_translate("AudioPhil", "Remove from playlist", None))
        self.playlistRemoveAction.setToolTip(_translate("AudioPhil", "Remove selected media from the current playlist", None))
        self.muteAction.setText(_translate("AudioPhil", "Mute", None))
        self.muteAction.setShortcut(_translate("AudioPhil", "M", None))
        self.renamePlaylistAction.setText(_translate("AudioPhil", "Rename current Playlist", None))
        self.renamePlaylistAction.setShortcut(_translate("AudioPhil", "F2", None))
        self.playbackModeRepeatTrackAction.setText(_translate("AudioPhil", "Repeat Track", None))
        self.playbackModeRepeatPlaylistAction.setText(_translate("AudioPhil", "Repeat Playlist", None))
        self.playbackModeRandomAction.setText(_translate("AudioPhil", "Random Track", None))
        self.playbackModeRandomPlaylistAction.setText(_translate("AudioPhil", "Random Playlist", None))
        self.stopAfterCurrentAction.setText(_translate("AudioPhil", "Stop after Current", None))
        self.playlistSearchAction.setText(_translate("AudioPhil", "Search Playlist...", None))
        self.playlistSearchAction.setShortcut(_translate("AudioPhil", "Ctrl+F", None))
        self.actionAbout.setText(_translate("AudioPhil", "About", None))
        self.actionAbout.setToolTip(_translate("AudioPhil", "About this Program", None))
        self.actionAbout.setShortcut(_translate("AudioPhil", "F1", None))
        self.savePlaylistAction.setText(_translate("AudioPhil", "Save Playlist...", None))
        self.savePlaylistAction.setToolTip(_translate("AudioPhil", "Save current Playlist", None))
        self.savePlaylistAction.setShortcut(_translate("AudioPhil", "Ctrl+S", None))
        self.showSidebarAction.setText(_translate("AudioPhil", "Show Sidebar", None))
        self.showMediaLibraryAction.setText(_translate("AudioPhil", "Show Media Library", None))
        self.openPlaylistsAction.setText(_translate("AudioPhil", "&Open Playlists...", None))
        self.openPlaylistsAction.setToolTip(_translate("AudioPhil", "open one or more playlist(s)", None))
        self.openPlaylistsAction.setShortcut(_translate("AudioPhil", "Ctrl+O", None))

from mediaLibrary import MediaLibrary
from playlists import Playlists
import audiophil_rc
